rbac:
  create: true

controller:
  # -- Controller log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
  logLevel: info

speaker:
  enabled: true
  # -- Speaker log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
  logLevel: info
  tolerateMaster: true

frrk8s:
  # if set, enables frrk8s as a backend. This is mutually exclusive to frr
  # mode.
  enabled: false
  external: false
  namespace: ""

