kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
        localAPIEndpoint:
          advertiseAddress: "172.18.0.2"
        ---
        kind: ClusterConfiguration
        networking:
          apiServer:
            advertiseAddress: "172.18.0.2" 
  - role: worker
  - role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."harbor.localhost.com"]
      endpoint = ["https://harbor.localhost.com"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor.localhost.com".tls]
        insecure_skip_verify = true
      
