replicaCount: 1

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.localhost.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  create: true
  mount: true
  claimName: gitea-shared-storage
  size: 1Gi
  accessModes:
    - ReadWriteOnce

gitea:
  admin:
    existingSecret: gitea-admin-secret

redis-cluster:
  enabled: false

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      size: 1Gi
