repositories:
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx/
- name: jenkins
  url: https://charts.jenkins.io
- name: gitea-charts
  url: https://dl.gitea.com/charts/

commonLabels:
  managed-by: helmfile

releases:
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb
  version: 0.14.7
  values:
  - /home/kind/gitflow/values/metallb/values.yaml

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  values:
  - /home/kind/gitflow/values/ingress-nginx/values.yaml

- name: jenkins
  namespace: jenkins
  chart: jenkins/jenkins
  version: 5.4.3
  values:
  - /home/kind/gitflow/values/jenkins/values.yaml

- name: gitea
  namespace: gitea
  chart: gitea-charts/gitea
  version: 10.4.0
  values:
  - /home/kind/gitflow/values/gitea/values.yaml
