apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: setup-hosts
  namespace: utils
  labels:
    k8s-app: setup-hosts
spec:
  selector:
    matchLabels:
      name: setup-hosts
  template:
    metadata:
      labels:
        name: setup-hosts
    spec:
      containers:
      - name: pause-container
        image: gcr.io/google-containers/pause:2.0
      volumes:
      - name: etc
        hostPath:
          path: /etc/
      initContainers:
      - name: setup-hosts
        image: busybox
        # not always kind assigns the same IP address to control-plane
        # unfortunately there is no workaround solution to this issue
        command:
          - /bin/sh
          - -c
          - grep -q jenkins.localhost.com /etc/hosts || echo "172.18.0.2 argocd.localhost.com jenkins.localhost.com gitea.localhost.com sonarqube.localhost.com harbor.localhost.com" >> /tmp/etc/hosts
        volumeMounts:
        - name: etc
          mountPath: /tmp/etc/

