# utils-pool: 172.18.0.16/28
# apps-pool: 172.18.0.32/28

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: utils-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.16/28
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: utils-advertisor
  namespace: metallb-system
spec:
  ipAddressPools:
  - utils-pool
